# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- master
 
pool:
  vmImage: ubuntu-latest
 
steps:
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'waws-prod-dm1-303.ftp.azurewebsites.windows.net'
    username: '$cloudastro-yll-test'
    password: 'YcA7vJvnNQSGxoFvtoXhmfYwAyFLMjkXA2aar7vSawdZhdKlDKPXs8ZghH1K'
    rootDirectory: 'src'
    filePatterns: '**'
    remoteDirectory: '/site/wwwroot'
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: false
