# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Pipeline
 
on: push
 
trigger:
- master
 
pool:
  vmImage: ubuntu-latest

jobs:
 my_job:
   steps:
   - task: FtpUpload@2
     inputs:
       credentialsOption: 'inputs'
       serverUrl: 'waws-prod-dm1-303.ftp.azurewebsites.windows.net'
       username: '$cloudastro-yll-test'
       password: 'YcA7vJvnNQSGxoFvtoXhmfYwAyFLMjkXA2aar7vSawdZhdKlDKPXs8ZghH1K'
       rootDirectory: 'src'
       filePatterns: '**'
       remoteDirectory: '/site/wwwroot'
       clean: false
       cleanContents: false
       preservePaths: true
       trustSSL: false
